"""comment

Revision ID: 94451e0fe22e
Revises: 703308338f63
Create Date: 2022-07-03 11:06:38.304157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94451e0fe22e'
down_revision = '703308338f63'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shaas_order', sa.Column('comment', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shaas_order', 'comment')
    # ### end Alembic commands ###
