"""options_id

Revision ID: 703308338f63
Revises: 390b235b1276
Create Date: 2022-07-03 10:14:28.203379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '703308338f63'
down_revision = '390b235b1276'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shaas_event', sa.Column('poll_options', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shaas_event', 'poll_options')
    # ### end Alembic commands ###
