"""chat

Revision ID: f991e133c447
Revises: 87be55b542ae
Create Date: 2022-07-17 09:46:29.702406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f991e133c447'
down_revision = '87be55b542ae'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shaas_chat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chat_id')
    )
    op.create_index(op.f('ix_shaas_chat_id'), 'shaas_chat', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shaas_chat_id'), table_name='shaas_chat')
    op.drop_table('shaas_chat')
    # ### end Alembic commands ###
