"""order taken

Revision ID: 390b235b1276
Revises: f4fc0e287165
Create Date: 2022-07-03 10:01:38.876940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '390b235b1276'
down_revision = 'f4fc0e287165'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shaas_order', sa.Column('is_taken', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shaas_order', 'is_taken')
    # ### end Alembic commands ###
