"""reorder order entiry

Revision ID: cb124d002ea3
Revises: f991e133c447
Create Date: 2022-07-17 16:04:17.248749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb124d002ea3'
down_revision = 'f991e133c447'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shaas_order_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('option_id', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['option_id'], ['shaas_menu_item.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['shaas_order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shaas_order_entry_id'), 'shaas_order_entry', ['id'], unique=False)
    op.drop_index('ix_shaas_order_comment_id', table_name='shaas_order_comment')
    op.drop_table('shaas_order_comment')
    op.add_column('shaas_order', sa.Column('comment', sa.String(), nullable=True))
    op.drop_constraint('shaas_order_option_fkey', 'shaas_order', type_='foreignkey')
    op.drop_column('shaas_order', 'option')
    op.drop_column('shaas_order', 'count')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shaas_order', sa.Column('count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('shaas_order', sa.Column('option', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('shaas_order_option_fkey', 'shaas_order', 'shaas_menu_item', ['option'], ['id'])
    op.drop_column('shaas_order', 'comment')
    op.create_table('shaas_order_comment',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('comment', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['shaas_event.id'], name='shaas_order_comment_event_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='shaas_order_comment_pkey')
    )
    op.create_index('ix_shaas_order_comment_id', 'shaas_order_comment', ['id'], unique=False)
    op.drop_index(op.f('ix_shaas_order_entry_id'), table_name='shaas_order_entry')
    op.drop_table('shaas_order_entry')
    # ### end Alembic commands ###
