"""menu pictures

Revision ID: 35da919ac385
Revises: 31f0b6bc6953
Create Date: 2022-07-17 18:41:10.454940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35da919ac385'
down_revision = '31f0b6bc6953'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shaas_menu_item', sa.Column('picture', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shaas_menu_item', 'picture')
    # ### end Alembic commands ###
