"""comment2

Revision ID: 9c2d7f839905
Revises: 94451e0fe22e
Create Date: 2022-07-03 11:13:40.075540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c2d7f839905'
down_revision = '94451e0fe22e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shaas_order_comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('fullname', sa.String(), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['shaas_event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shaas_order_comment_id'), 'shaas_order_comment', ['id'], unique=False)
    op.drop_column('shaas_order', 'comment')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shaas_order', sa.Column('comment', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_shaas_order_comment_id'), table_name='shaas_order_comment')
    op.drop_table('shaas_order_comment')
    # ### end Alembic commands ###
