"""init

Revision ID: e89cab65ce19
Revises: 
Create Date: 2022-07-02 19:52:31.520355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e89cab65ce19'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shaas_menu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shaas_menu_id'), 'shaas_menu', ['id'], unique=False)
    op.create_table('shaas_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state', sa.Enum('collecting_orders', 'delivery', 'finished', name='eventstate'), nullable=True),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('poll_message_id', sa.BigInteger(), nullable=False),
    sa.Column('poll_id', sa.String(), nullable=False),
    sa.Column('collect_message_id', sa.BigInteger(), nullable=True),
    sa.Column('skip_option', sa.Integer(), nullable=False),
    sa.Column('menu_id', sa.Integer(), nullable=True),
    sa.Column('available_slots', sa.Integer(), server_default='0', nullable=True),
    sa.Column('delivery_info', sa.String(), server_default='', nullable=True),
    sa.Column('order_end_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['menu_id'], ['shaas_menu.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shaas_event_id'), 'shaas_event', ['id'], unique=False)
    op.create_table('shaas_menu_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('menu_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('proteins', sa.Float(), nullable=True),
    sa.Column('fats', sa.Float(), nullable=True),
    sa.Column('carbohydrates', sa.Float(), nullable=True),
    sa.Column('calories', sa.Float(), nullable=True),
    sa.Column('poll_enable', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['menu_id'], ['shaas_menu.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shaas_menu_item_id'), 'shaas_menu_item', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shaas_menu_item_id'), table_name='shaas_menu_item')
    op.drop_table('shaas_menu_item')
    op.drop_index(op.f('ix_shaas_event_id'), table_name='shaas_event')
    op.drop_table('shaas_event')
    op.drop_index(op.f('ix_shaas_menu_id'), table_name='shaas_menu')
    op.drop_table('shaas_menu')
    # ### end Alembic commands ###
