"""comment3

Revision ID: 87be55b542ae
Revises: 9c2d7f839905
Create Date: 2022-07-03 11:14:39.352370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87be55b542ae'
down_revision = '9c2d7f839905'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shaas_order_comment', 'fullname')
    op.drop_column('shaas_order_comment', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shaas_order_comment', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('shaas_order_comment', sa.Column('fullname', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
