"""order

Revision ID: f4fc0e287165
Revises: e89cab65ce19
Create Date: 2022-07-02 19:55:35.537144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4fc0e287165'
down_revision = 'e89cab65ce19'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shaas_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('option', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['shaas_event.id'], ),
    sa.ForeignKeyConstraint(['option'], ['shaas_menu_item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shaas_order_id'), 'shaas_order', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shaas_order_id'), table_name='shaas_order')
    op.drop_table('shaas_order')
    # ### end Alembic commands ###
