"""channel_id

Revision ID: 041386caeb99
Revises: b559300ac7ff
Create Date: 2023-09-14 05:48:03.553936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '041386caeb99'
down_revision = 'b559300ac7ff'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shaas_event', sa.Column('channel_id', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shaas_event', 'channel_id')
    # ### end Alembic commands ###
