"""user settings

Revision ID: 09620ae87e9c
Revises: e95209f0362b
Create Date: 2023-03-19 11:17:52.489622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09620ae87e9c'
down_revision = 'e95209f0362b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shaas_chat', sa.Column('send_direct_messages', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shaas_chat', 'send_direct_messages')
    # ### end Alembic commands ###
