"""token

Revision ID: 701393b5551d
Revises: 0596c483776d
Create Date: 2023-01-04 10:15:45.500311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '701393b5551d'
down_revision = '0596c483776d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shaas_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('expires_in', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['shaas_chat.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shaas_token_id'), 'shaas_token', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shaas_token_id'), table_name='shaas_token')
    op.drop_table('shaas_token')
    # ### end Alembic commands ###
