"""leftovers

Revision ID: d3cc5f4389d6
Revises: 701393b5551d
Create Date: 2023-01-04 17:27:01.829790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3cc5f4389d6'
down_revision = '701393b5551d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shaas_menu_item', sa.Column('leftover', sa.Integer(), server_default='100', nullable=True))
    op.drop_column('shaas_menu_item', 'poll_enable')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shaas_menu_item', sa.Column('poll_enable', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('shaas_menu_item', 'leftover')
    # ### end Alembic commands ###
