"""bonuses

Revision ID: 0596c483776d
Revises: e041af4ed8fa
Create Date: 2023-01-03 13:05:56.632452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0596c483776d'
down_revision = 'e041af4ed8fa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shaas_chat', sa.Column('available_bonuses', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shaas_chat', 'available_bonuses')
    # ### end Alembic commands ###
