"""actual order end time

Revision ID: 016bbd33722d
Revises: 33c8794c9d73
Create Date: 2023-05-06 11:25:46.242304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '016bbd33722d'
down_revision = '33c8794c9d73'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shaas_event', sa.Column('actual_order_end_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shaas_event', 'actual_order_end_time')
    # ### end Alembic commands ###
