"""chat recognition

Revision ID: d7cc6c5443aa
Revises: 6f773ad31b59
Create Date: 2023-01-02 15:48:15.627843

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd7cc6c5443aa'
down_revision = '6f773ad31b59'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shaas_chat', sa.Column('name', sa.String(), nullable=True))
    op.add_column('shaas_chat', sa.Column('username', sa.String(), nullable=True))
    op.drop_index('ix_shaas_chat_id', table_name='shaas_chat')
    op.drop_constraint('shaas_chat_chat_id_key', 'shaas_chat', type_='unique')
    op.create_unique_constraint(None, 'shaas_chat', ['id'])
    op.drop_column('shaas_chat', 'chat_id')
    op.add_column('shaas_event', sa.Column('owner_id', sa.BigInteger(), nullable=True))
    op.drop_column('shaas_event', 'poll_id')
    op.drop_column('shaas_event', 'poll_options')
    op.drop_column('shaas_event', 'poll_message_id')
    op.drop_column('shaas_event', 'skip_option')
    # ### end Alembic commands ###

    op.execute("alter table shaas_chat alter column id type bigint using id::bigint;")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shaas_event', sa.Column('skip_option', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('shaas_event', sa.Column('poll_message_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('shaas_event', sa.Column('poll_options', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('shaas_event', sa.Column('poll_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('shaas_event', 'owner_id')
    op.add_column('shaas_chat', sa.Column('chat_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'shaas_chat', type_='unique')
    op.create_unique_constraint('shaas_chat_chat_id_key', 'shaas_chat', ['chat_id'])
    op.create_index('ix_shaas_chat_id', 'shaas_chat', ['id'], unique=False)
    op.drop_column('shaas_chat', 'username')
    op.drop_column('shaas_chat', 'name')
    # ### end Alembic commands ###

    op.execute("alter table shaas_chat alter column id type integer using id::integer;")