"""lucky entry

Revision ID: 15be1a0e1587
Revises: 016bbd33722d
Create Date: 2023-05-06 12:19:43.219205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15be1a0e1587'
down_revision = '016bbd33722d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shaas_lucky_attempt',
    sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('menu_item_id', sa.Integer(), nullable=False),
    sa.Column('accepted', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['shaas_event.id'], ),
    sa.ForeignKeyConstraint(['menu_item_id'], ['shaas_menu_item.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['shaas_chat.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shaas_lucky_attempt_id'), 'shaas_lucky_attempt', ['id'], unique=False)
    op.add_column('shaas_chat', sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('shaas_chat', sa.Column('updated', sa.DateTime(), nullable=True))
    op.add_column('shaas_coupon', sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('shaas_coupon', sa.Column('updated', sa.DateTime(), nullable=True))
    op.add_column('shaas_event', sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('shaas_event', sa.Column('updated', sa.DateTime(), nullable=True))
    op.add_column('shaas_menu', sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('shaas_menu', sa.Column('updated', sa.DateTime(), nullable=True))
    op.add_column('shaas_menu_item', sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('shaas_menu_item', sa.Column('updated', sa.DateTime(), nullable=True))
    op.add_column('shaas_order', sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('shaas_order', sa.Column('updated', sa.DateTime(), nullable=True))
    op.add_column('shaas_order_entry', sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('shaas_order_entry', sa.Column('updated', sa.DateTime(), nullable=True))
    op.add_column('shaas_token', sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('shaas_token', sa.Column('updated', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shaas_token', 'updated')
    op.drop_column('shaas_token', 'created')
    op.drop_column('shaas_order_entry', 'updated')
    op.drop_column('shaas_order_entry', 'created')
    op.drop_column('shaas_order', 'updated')
    op.drop_column('shaas_order', 'created')
    op.drop_column('shaas_menu_item', 'updated')
    op.drop_column('shaas_menu_item', 'created')
    op.drop_column('shaas_menu', 'updated')
    op.drop_column('shaas_menu', 'created')
    op.drop_column('shaas_event', 'updated')
    op.drop_column('shaas_event', 'created')
    op.drop_column('shaas_coupon', 'updated')
    op.drop_column('shaas_coupon', 'created')
    op.drop_column('shaas_chat', 'updated')
    op.drop_column('shaas_chat', 'created')
    op.drop_index(op.f('ix_shaas_lucky_attempt_id'), table_name='shaas_lucky_attempt')
    op.drop_table('shaas_lucky_attempt')
    # ### end Alembic commands ###
