"""ordered state

Revision ID: b559300ac7ff
Revises: 15be1a0e1587
Create Date: 2023-05-07 15:30:12.989891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b559300ac7ff'
down_revision = '15be1a0e1587'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shaas_order', sa.Column('is_paid', sa.Boolean(), server_default=sa.text('false'), nullable=True))
    op.add_column('shaas_order_entry', sa.Column('is_ordered', sa.Boolean(), server_default=sa.text('false'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shaas_order_entry', 'is_ordered')
    op.drop_column('shaas_order', 'is_paid')
    # ### end Alembic commands ###
