"""bonuses

Revision ID: e95209f0362b
Revises: d3cc5f4389d6
Create Date: 2023-01-05 09:19:15.047487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e95209f0362b'
down_revision = 'd3cc5f4389d6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shaas_coupon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('count', sa.Integer(), server_default='0', nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'user_id', name='_owner_user')
    )
    op.create_index(op.f('ix_shaas_coupon_id'), 'shaas_coupon', ['id'], unique=False)
    op.drop_column('shaas_chat', 'available_bonuses')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shaas_chat', sa.Column('available_bonuses', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_shaas_coupon_id'), table_name='shaas_coupon')
    op.drop_table('shaas_coupon')
    # ### end Alembic commands ###
