"""menu item category

Revision ID: 33c8794c9d73
Revises: 09620ae87e9c
Create Date: 2023-04-03 09:19:16.932155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33c8794c9d73'
down_revision = '09620ae87e9c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shaas_menu_item', sa.Column('category', sa.String(), server_default='default', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shaas_menu_item', 'category')
    # ### end Alembic commands ###
