"""channel_id collect_message

Revision ID: 322df248f460
Revises: 041386caeb99
Create Date: 2023-09-14 06:03:17.753502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '322df248f460'
down_revision = '041386caeb99'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shaas_event', sa.Column('channel_collect_message_id', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shaas_event', 'channel_collect_message_id')
    # ### end Alembic commands ###
