"""is_enabled menu_item

Revision ID: 864a8a31b87e
Revises: 322df248f460
Create Date: 2024-07-03 18:14:38.058338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '864a8a31b87e'
down_revision = '322df248f460'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shaas_menu_item', sa.Column('is_enabled', sa.Boolean(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shaas_menu_item', 'is_enabled')
    # ### end Alembic commands ###
